[package]
name = "pyo3_interior_mutability_experiment"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pyo3 = {version = "0.24", features = ["auto-initialize", "extension-module"]}